name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub

        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
          REPO_NAME: ${{secrets.REPO_NAME}}

        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t $DOCKER_USER/$REPO_NAME:latest

      - name: push the docker image
        id: push-docker-image
        run: docker push $DOCKER_USER/$REPO_NAME:latest
